### ISSUE TITLE
Add "getting started" to the read me

### ISSUE THREAD

**Issue by inooid** [Mstiekema/Yucibot#4]
In order to get this project up and running it might be smart to add a _"Getting Started"_ section to the `README.md`. This will make it easier for people to hop on and use the bot. 😁 

Maybe even a section about the _"Requirements"_ before running this. As far as I've seen it uses Node, MySQL, etc.

**Comment by Mstiekema** [comment]
I had already made an installation guide in the Wiki, but added it to the README for more visibility 👍
